version: "3.9"
services:
  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_net
  flaskapp:
    build: ./flaskapp
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net:
